export default {
  namespaced: true,
  state: {
    tableData: [
      {
        id: 1,
        roleName: "财务人员",
        personNum: 3,
        role: "理财务类的相关事务",
        createTime: "2022-08-10 18:22:40",
        state: "正常",
      },
      {
        id: 2,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 3,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 4,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 5,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 6,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 7,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 8,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },
      {
        id: 9,
        roleName: "用户审核员",
        personNum: 2,
        role: "处理普通用户的相关事务",
        createTime: "2022-08-10 18:20:40",
        state: "正常",
      },

    ],
  },
  getters: {},
  mutations: {},
  actions: {},
}